# Generated by Django 2.2.6 on 2019-10-15 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('conference_minister', models.OneToOneField(on_delete='do_nothing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
